language: ruby
rvm:
  - 2.2.3
script: bundle exec rake test
before_deploy:
  - bundle exec rake gem:build
  - export GEM_FILE="$(ls -1 pkg/*.gem | tail -n1)"
deploy:
  - provider: rubygems
    api_key: $RUBYGEMS_KEY
    gem: rbstruct
    on:
      tags: true
      repo: kaffepanna/rbtelldus
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file: ${GEM_FILE}
    file_glob: true
    on:
      tags: true
      repo: kaffepanna/rbstruct
